package com.notsecure.Appointees.model;

public enum PermissionCodes {
   W_BR,R_APPTS_ALL,W_APPTS_ALL,R_APPTS_OWN,W_APPTS_OWN,R_SVCS_ALL,W_SVCS_ALL,R_WRK_HRS,W_WRK_HRS,R_CLS_BR,R_CLS_CO,R_CLS_OWN,W_CLS_BR,W_CLS_CO,W_CLS_OWN,
   R_USRPF_OWN,W_USRPF_OWN,R_USRPF_BR,W_USRPRFL_BR,R_USRPF_CO,W_USRPF_CO;
}
